### ISSUE TITLE
Negative number in input textbox

### ISSUE THREAD

**Issue by gaoteng-git** [pytorch/kineto#161]
In Operator view, now user can input negative number into the "Top kernels to show". This should be forbidden.
The way to reproduce it:
1. Mouse move to head of the number, click.
2. Input the negative character "-", press enter key.

![image](https://user-images.githubusercontent.com/10429114/114505021-5616e080-9c62-11eb-944d-6c3187c8f159.png)

![image](https://user-images.githubusercontent.com/10429114/114502325-2ebe1480-9c5e-11eb-86e9-32624186fd1e.png)

**Comment by TomWildenhain-Microsoft** [comment]
@gaoteng-git check if #168 does what you want.  Users can enter any valid number, but invalid inputs will make the field turn red and be ignored.  This is useful since some values (empty string) may themselves be invalid but useful intermediate steps for entering a valid entry (it is annoying to have it constantly replace empty string with 0 as it does now).

The prohibition of entering non-numeric characters is happening in Chrome and unfortunately cannot be edited, so ".", "-" and "e" can all be entered but will be ignored (and make the field red).
