### ISSUE TITLE
Page scroll up

### ISSUE THREAD

**Issue by gaoteng-git** [pytorch/kineto#162]
Scroll the page down:
![image](https://user-images.githubusercontent.com/10429114/114506174-ffaaa180-9c63-11eb-9bac-abb5e0f5cd4f.png)

Input a string into "Search by Name" and press enter:
![image](https://user-images.githubusercontent.com/10429114/114511052-fde3dc80-9c69-11eb-8320-ee43644c73c9.png)

The page is automatically scrolled up. It is not a good user experience which makes user lose focus.

The "Group By" still behave like this. 
The "Group By" and "Search by Name" in "Kernel View" also behave like this.

**Comment by TomWildenhain-Microsoft** [comment]
The scrolling is caused by the table redraw.  When the table is deleted, the page scrolls up.  As long as this doesn't bring us to the very top of the page, Chrome scrolls back down when the table is re-added, but on the Kernels page it is too short so it gets stuck at the top and doesn't go back.  Probably the best solution would be hooking the table redraw to add a placeholder box while drawing so the page height doesn't change.

**Comment by gaoteng-git** [comment]
Solved by PR https://github.com/pytorch/kineto/pull/183
