### ISSUE TITLE
Difference between 2 namespaces: libkineto and KINETO_NAMESPACE

### ISSUE THREAD

**Issue by liuyibox** [pytorch/kineto#310]
Hi I'm wondering if there is any story behind these 2 namespace names? Are these 2 namespaces covering 2 different code scopes or serving different purposes?

I see many places they are using each other, this makes me confused about the design logic of the 2 namespaces. For example, in "src/CuptiActivity.h", KINETO_NAMESPACE is `using namespace libkineto`, whereas in "src/output_base.h", libkineto is "using namespace KINETO_NAMESPACE". 

It seems they are interleaved/used with each other, is this against the usage philosophy of c++ namespace? Thanks.

**Comment by robieta** [comment]
Just came across this, so I figured I'd set the record straight. (Albeit far too late.) Kineto changed names early in the development, and this was a tool to migrate things around using a `-DKINETO_NAMESPACE=...` flag. We're going to consolidate to `namespace libkineto`, since that migration is long done.
