### ISSUE TITLE
Trace arbitrary python code

### ISSUE THREAD

**Issue by maximilian-tech** [pytorch/kineto#597]
Hello,

is it possible to trace arbitrary python code without setting the "with_stack=True" flag? I would like to get a reduced information about the functions executed, without information about the file and line the function was called from.

I hope this will have a lower overhead than it has at the moment.

Thanks!

**Comment by robieta** [comment]
No, that is not possible. Including the filename and line number doesn't really affect the overhead due to the way the cache structure works. (Unless you have a very low cache hit rate due to unusual code flow, in which case there's not much we can do.) I do have a change in the pipeline that will cut overhead by ~15%; past that you sort of run into the limits of what is possible. Profiling adds overhead no matter what profiler you use.
