### ISSUE TITLE
Link stack trace to exact line of source file

### ISSUE THREAD

**Issue by latkins** [pytorch/kineto#630]
Is it possible to link a pytorch operation to the exact line of a source file using kineto's stack trace? For example, the following function 
![image](https://user-images.githubusercontent.com/1080217/179358979-92d27b79-6f7e-4780-b10a-a18a50f84660.png)
has traces that look like 
```
""Call stack": "main.py(104): <module>;main.py(38): do_profile;naive_attn.py(71): run_model;nn.Module: Sequential_0;torch/nn/modules/container.py(152): forward;nn.Module: SelfAttn_0;naive_attn.py(55): forward;naive_attn.py(20): forward;naive_attn.py(23): <listcomp>;nn.Module: AttnHead_7;naive_attn.py(39): forward;naive_attn.py(45): attn;torch/nn/functional.py(1811): softmax;<built-in method permute of Tensor object at 0x7fe4c46fbe20>;"
```
That is, the torch operation is only "linked" to the whole function's scope (e.g. `naive_attn.py(45): attn`, rather than `naive_attn.py(50)`). 

(I thought that the profiler released with pytorch 1.8 did this, though I may be mistaken)

**Comment by robieta** [comment]
I think you've actually found a bug in the profiler. Circa 1.8 `with_stack` would snapshot the current cPython stack. This was prohibitively expensive / wasteful and made it impossible to get meaningful times with it enabled. To address this we switched to a replay based system that keeps track of when we enter and exit frames and reconstruct the python stack during post processing. But what your post makes me realize is that capturing the frame when we enter a function and snapshotting the stack when we call an op differ in where in the frame we are.

Luckily I recently refactored the profiler so that whenever the python tracer records an event it now also records the frame of the caller ([code](https://github.com/pytorch/pytorch/blob/30fb2c4abaaaa966999eab11674f25b18460e609/torch/csrc/autograd/profiler_python.cpp#L339)), which may have changed since the first time we saw the frame. So it should be a pretty simple fix to tweak the trace generation code to use the caller information.

Thanks for the report!
CC @slgong-fb @chaekit
