### ISSUE TITLE
what is happen when I use torch.profiler.profile with activities=[torch.profiler.ProfilerActivity.CPU, torch.profiler.ProfilerActivity.CUDA]

### ISSUE THREAD

**Issue by qq1243196045** [pytorch/kineto#681]
I use profiler with `activities=[torch.profiler.ProfilerActivity.CPU, torch.profiler.ProfilerActivity.CUDA]`, and get time 0.22ms in cpu time , avg 5.14us in cuda time, and when I use `time.time()` with `torch.cuda.synchronize()`,the result is 0.24 ms. What is the difference between these results？
My code looks like:
```
activities = [torch.profiler.ProfilerActivity.CPU, torch.profiler.ProfilerActivity.CUDA]
torch.cuda.synchronize()
start = time.time()
with torch.profiler.profile(activities= activities, record_shapes=True, profile_memory=False) as pf:
    output = model(input)
torch.cuda.synchronize()
end = time.time()
runtime = end-start()
```

**Comment by briancoutinho** [comment]
Since you are measuring CUDA activities the profiler initializes and uses NVIDIA's CUPTI (CUDA profiling library). This will have some amount of overhead because CUDA runtime instruments the GPU kernels. 
https://docs.nvidia.com/cupti/r_main.html#r_overhead

As a suggestion try adding a for loop for your model for example ` for ..: output= model(input)`, if the overhead increases proportionally there might be something going on, and we need to check.
Also, if you disable CUDA the overhead should be lower.

The duration you are measuring is quite small so this maybe significant I think. @chaekit , @aaronenyeshi  any other details to add.

**Comment by aaronenyeshi** [comment]
Could you please share the code snippets before and after? And their timestamps. The original comment was hard to figure out what has changed.
