### ISSUE TITLE
Windows: CUDA kernels are not recorded as expected.

### ISSUE THREAD

**Issue by wangruohui** [pytorch/kineto#762]
Hello,

I am trying to follow the instruction https://github.com/pytorch/kineto/tree/main/tb_plugin#quick-start-instructions and hope to visualize CUDA kernels. But I can't find "async" in "Flow events" in my view.

I run programs on a GeForce 2080Ti on Windows. Does this feature not support on my platform?

### My steps
- Download and run https://github.com/pytorch/kineto/blob/main/tb_plugin/examples/resnet50_profiler_api.py. (On Windows, I need to add `if __name__ == "__main__":` to launch multiple dataloader workers successfully, see attached for details)
- Open Tensorboard via `tensorboard --logdir result`

As this image shows, nothing is found in "Flow events". Only operations at or above ATen level are recorded, which are actually all CPU operations. 
![image](https://github.com/pytorch/kineto/assets/12756472/f95a8d45-daaf-4551-a1bb-040903cf1ef9)
However, this code does call `.cuda()` and I can visualize GPU activities in Windows task manager. 

I expect to see CUDA calls like [this](https://github.com/pytorch/kineto/blob/main/tb_plugin/docs/images/trace_view_launch.PNG) as shown in the instruction.

### Other tries
- I tried in WSL2 on the same machine, same result as Windows native. 
- I downloaded the provided [samples](https://github.com/pytorch/kineto/tree/main/tb_plugin/samples). CUDA calls are displays correctly.

### My profiling data
[worker0.1684785072247.pt.trace.txt](https://github.com/pytorch/kineto/files/11575321/worker0.1684785072247.pt.trace.txt)
Actually, items like `"cat": "Kernel"`, `cudaLaunchKernel` can not be found. Only `"cat": "cpu_op"` are recorded. 

### Modified code on Windows
```
import torch
# ... same content as original
import torch.profiler

if __name__ == '__main__':
    model = models.resnet50(pretrained=True)
    # ... same content as original but with indent
```

### My Env
```
PyTorch version: 2.0.1
Is debug build: False
CUDA used to build PyTorch: 11.8
ROCM used to build PyTorch: N/A

OS: Microsoft Windows 11 企业版 Insider Preview
GCC version: Could not collect
Clang version: Could not collect
CMake version: Could not collect
Libc version: N/A

Python version: 3.10.10 | packaged by Anaconda, Inc. | (main, Mar 21 2023, 18:39:17) [MSC v.1916 64 bit (AMD64)] (64-bit runtime)
Python platform: Windows-10-10.0.23451-SP0
Is CUDA available: True
CUDA runtime version: Could not collect
CUDA_MODULE_LOADING set to: LAZY
GPU models and configuration: GPU 0: NVIDIA GeForce RTX 2080 Ti
Nvidia driver version: 531.68
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Architecture=9
CurrentClockSpeed=3600
DeviceID=CPU0
Family=205
L2CacheSize=1536
L2CacheSpeed=
Manufacturer=GenuineIntel
MaxClockSpeed=3600
Name=Intel(R) Core(TM) i5-8600K CPU @ 3.60GHz
ProcessorType=3
Revision=

Versions of relevant libraries:
[pip3] mypy-extensions==1.0.0
[pip3] numpy==1.23.5
[pip3] torch==2.0.1
[pip3] torch-tb-profiler==0.4.1
[pip3] torchaudio==2.0.2
[pip3] torchvision==0.15.0
[conda] Could not collect
```

**Comment by shenmishajing** [comment]
Same issue! Can not record CUDA kernels on Ubuntu 18.04 with pytorch==1.13.1, pytorch-cuda==11.7 and 4090 GPUs.

**Comment by aaronenyeshi** [comment]
Windows is not implemented, see https://github.com/pytorch/kineto/issues/356. Feel free to contribute any PRs to enable on Windows!

**Comment by pchng** [comment]
So, I think I have an idea why PyTorch profiling of CUDA devices doesn't work on WSL (i.e. when running Ubuntu on Windows vs. WSL) I believe this issue is separate from any issues surrounding running PyTorch Profiler/Kineto on _native_ Windows.

This _specific_ issue of PyTorch Profiler/Kineto **not** being able to trace/record CUDA stream events, and _only_ showing the CPU trace, despite all configurations/settings being correct (e.g. setting `ProfilerActivity.CUDA`) has been reported a few times. In particular, the GPU traces still do not show up even after [enabling driver permissions described here](https://developer.nvidia.com/nvidia-development-tools-solutions-err_nvgpuctrperm-permission-issue-performance-counters).

Here are a few for reference:
1. https://github.com/pytorch/pytorch/issues/99615#issuecomment-1824689341 (note this particular comment where user says "_As of writing this, kineto no longer writes that error message, but that being said, it doens't collect any events either. I'll continue investigation._")
2. https://github.com/pytorch/pytorch/issues/124547

For reference, here's what I see on my WSL 2 Ubuntu system with a sample workload:
```
KINETO_LOG_LEVEL=0 KINETO_ENABLE_EVENT_PROFILER=1 ./model.py
torch.__version__='2.1.2+cu121'
torch.autograd._supported_activities()={<ProfilerActivity.CPU: 0>, <ProfilerActivity.CUDA: 2>}
torch.Size([8])
torch.Size([8])
CUDA available: True. Using device=device(type='cuda')
INFO:2025-03-01 11:23:28 22862:22862 CuptiActivityProfiler.cpp:203] CUDA versions. CUPTI: 18; Runtime: 12010; Driver: 12060
  Log file: /tmp/libkineto_activities_22862.json
  Trace start time: 2025-03-01 11:23:35  Trace duration: 500ms
  Warmup duration: 5s
  Max GPU buffer size: 128MB
  Enabled activities: cpu_op,user_annotation,external_correlation,cuda_runtime,cuda_driver,cpu_instant_event,python_function,xpu_runtime
INFO:2025-03-01 11:23:28 22862:22862 CuptiActivityProfiler.cpp:797] Enabling GPU tracing
INFO:2025-03-01 11:23:28 22862:22862 CuptiActivityProfiler.cpp:836] Tracing starting in 6s
INFO:2025-03-01 11:23:28 22862:22862 CuptiActivityProfiler.cpp:841] Tracing will end in 7s
STAGE:2025-03-01 11:23:28 22862:22862 ActivityProfilerController.cpp:312] Completed Stage: Warm Up
STAGE:2025-03-01 11:23:28 22862:22862 ActivityProfilerController.cpp:318] Completed Stage: Collection
INFO:2025-03-01 11:23:28 22862:22862 CuptiActivityProfiler.cpp:210] Processing 1 CPU buffers
INFO:2025-03-01 11:23:28 22862:22862 CuptiActivityProfiler.cpp:240] Processed 35234 GPU records (1037712 bytes)
INFO:2025-03-01 11:23:28 22862:22862 CuptiActivityProfiler.cpp:1019] Traces Recorded:
INFO:2025-03-01 11:23:28 22862:22862 CuptiActivityProfiler.cpp:1022] PyTorch Profiler: 1 iterations
STAGE:2025-03-01 11:23:28 22862:22862 ActivityProfilerController.cpp:322] Completed Stage: Post Processing
INFO:2025-03-01 11:23:28 22862:22862 output_json.cpp:79] Tracing to temporary file trace.json
INFO:2025-03-01 11:23:28 22862:22862 output_json.cpp:385] Chrome Trace written to trace.json
INFO:2025-03-01 11:23:28 22862:22862 output_json.cpp:433] Renamed the trace file to trace.json
```

kineto is collecting the GPU traces (records) but I don't see those reflected in the output trace JSON for whatever reason. This is similar to reference (1) above.

I think the issue is this:
1. CUPTI is indeed supported on WSL ([Reference](https://docs.nvidia.com/cuda/wsl-user-guide/index.html#nvidia-compute-software-support-on-wsl-2))
2. However, the CUDA toolkit version you [download/install for WSL Ubuntu](https://developer.nvidia.com/cuda-downloads?target_os=Linux&target_arch=x86_64&Distribution=WSL-Ubuntu&target_version=2.0&target_type=deb_local) is **different** from the normal Ubuntu/Linux CUDA toolkit.
3. This leads me to believe that `libcupti` for the WSL CUDA install is also different/customized for WSL, for whatever reason.
4. From what I can tell kineto _statically links_ against `libcupti` (`libcupti_static.a`?) and _that_ version is probably the "regular" Linux one and not the WSL one.
5. To get it working, at a minimum, it seems like you'd have to (re)compile `libkineto` against the WSL `libcupti` version, then (re)compile PyTorch against the new version of `libkineto`, and then maybe this would work.
